# version: 0.2
# phases:
#   install:
#     commands:
#       - "apt install unzip -y"
#       - "wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip"
#       - "unzip terraform_1.0.5_linux_amd64.zip"
#       - "mv terraform /usr/local/bin/"
#     pre_build:
#       commands:
#         - cd "$CODEBUILD_SRC_DIR"
#         - terraform init
#         - terraform validate
  
#     build:
#       commands:
#         - terraform apply --auto-approve

#     post_build:
#       commands:
#         - echo terraform apply completed on `date`

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.0.1/terraform_1.0.1_linux_amd64.zip
      - unzip terraform_1.0.1_linux_amd64.zip
      - rm terraform_1.0.1_linux_amd64.zip
      - chmod +x terraform
      - export PATH=$PATH:$PWD
  build:
    commands:
      - terraform init
      - terraform validate
      
  post_build:
    commands:
      - terraform apply -auto-approve
      - echo terraform apply completed on `date`
      - terraform init -migrate-state -auto-approve
      - echo state file migrated to s3 completed on `date` 